# A docker-compose must always start by the version tag.
# We use '3' because it's the last version at this time.
version: "3"

# docker-compose works with services - 1 service = 1 container.
# A service may be, a server, a client, a database...
# We use the keyword 'services' to start to create services.
services:
  # We want to create two services/containers: a server and a client.

  # First service called "server" - you are free to choose
  # the keyword which defines what the service corresponds to
  server:
    # Keyword "build" to define the path to the Dockerfile
    # used to create the image, which allows you to execute the service.
    # Here 'server/' is the path to the Dockerfile
    build: server/

    # The command to execute once the image is created.
    # The following command will execute "python ./server.py".
    command: python ./server.py

    # Remember that we defined in'server/server.py' 1234 as port.
    # If we want to access the server from our computer (outside the container),
    # we must share the content port with our computer's port.
    # To do this, the keyword 'ports' will help us.
    # Syntax: [port we want on our machine]:[port we want to retrieve in the container]
    # In our case, we want to use port 1234 on our machine and
    # retrieve port 1234 from the container (because it is on this port that
    # we broadcast the server).
    ports:
      - 1234:1234

  # Second service (container): the client.
  client:
    # Here 'client/ corresponds to the path to the client folder
    # that contains the Dockerfile to use.
    build: client/

    # The command to execute once the image is created.
    # The following command will execute "python ./client.py".
    command: python ./client.py

    # The keyword 'network_mode' is used to define the network type.
    # Here we define that the container can access to the 'localhost' of the computer.
    network_mode: host

    # The keyword'depends_on' allows you to define whether the service
    # should wait until other services are ready before launching.
    # Here, we want the 'client' service to wait until the 'server' service is ready.
    depends_on:
      - server
